Repository jstz-dev/jstz, pull requests merged in 2023-10, with the labels that each got.

#35 Docs: Getting Started
  docs/.vitepress/config.mjs
  docs/first_steps.md
  docs/index.md
  docs/installation.md
  examples/hello-world/index.ts
  examples/hello-world/package.json
Labels: documentation, m9::documentation

#36 Docs: KV
  docs/.vitepress/config.mjs
  docs/api/index.md
  docs/api/kv.md
Labels: documentation, m9::documentation

#37 Docs: Ledger
  docs/.vitepress/config.mjs
  docs/api/index.md
  docs/api/ledger.md
Labels: documentation, m9::documentation

#34 Cli: Sandbox start/stop threads with bridge deploying
  Cargo.lock
  Cargo.toml
  jstz_cli/Cargo.toml
  jstz_cli/sandbox-params.json
  jstz_cli/sandbox.json
  jstz_cli/src/bridge/deposit.rs
  jstz_cli/src/bridge/mod.rs
  jstz_cli/src/config.rs
  jstz_cli/src/deploy.rs
  jstz_cli/src/deposit.rs
  jstz_cli/src/main.rs
  jstz_cli/src/octez.rs
  jstz_cli/src/run.rs
  jstz_cli/src/run_contract.rs
  jstz_cli/src/sandbox/daemon.rs
  jstz_cli/src/sandbox/mod.rs
  jstz_cli/src/utils.rs
Labels: jstz::cli, m7::cli

#47 Docs: Headers
  docs/.vitepress/config.mjs
  docs/api/headers.md
  docs/api/index.md
Labels: documentation, m9::documentation

#48 Docs: Response
  docs/.vitepress/config.mjs
  docs/api/index.md
  docs/api/response.md
Labels: documentation, m9::documentation

#49 Git: CI workflow
  .github/workflows/ci.yml
  .gitignore
  Makefile
  package-lock.json
  package.json
Labels: git

#55 Nix: Bump `boa_engine`
  Cargo.lock
  nix/jstz.nix
Labels: jstz::nix

#62 Bugfix: Incorrect `bridge_address` encoding
  Cargo.lock
  jstz_cli/Cargo.toml
  jstz_cli/src/sandbox/daemon.rs
Labels: bug

#60 Cli Repl: Automatically resolve promises and add last result variable
  jstz_cli/src/repl.rs
Labels: jstz::cli, m7::cli

#70 Git: Configure dependabot
  .github/dependabot.yml
Labels: git

#82 Docs: Request
  docs/.vitepress/config.mjs
  docs/api/index.md
  docs/api/request.md
Labels: documentation, m9::documentation

#53 Docs: URL
  docs/.vitepress/config.mjs
  docs/api/index.md
  docs/api/url.md
  docs/api/url_search_params.md
Labels: documentation, m9::documentation

#81 Cli: Responses
  Cargo.lock
  jstz_cli/Cargo.toml
  jstz_cli/src/config.rs
  jstz_cli/src/deploy.rs
  jstz_cli/src/jstz.rs
  jstz_cli/src/main.rs
  jstz_cli/src/run.rs
Labels: jstz::cli
